script: bash ./deploy.sh
language: node_js
node_js:
- "4.0"
env:
  global:
  - GH_REF: github.com/rikukissa/rikukissa.github.io.git
  - secure: "eTOfirWn9eGvT0JHlEQjP841dR/6SF/44LuRlf1bI2RPJGmiZYy2VSu2hfq/NOdxJ/pxZ5+reeb7uwKLPBx8OALYStRMO4nh23waDGcipXNUdJ3/JDJkPnitiTIDJbRPRRdZJTJltJI6QzEzB1N646fVomozfXstyDoV0p7npEXIvbmm2Rjyu/oRZV9900aZ5o2sj/Fxb7uK2Jh5xBdgDbm3gORpqTlpSZt0UvL0JNpUn98BQy9PLMaBFLaOjIRgDDOYIrqVp5teiACpGknX3Mx5t202laW6tXgzM/aayS7F7vqv0/4u0px5Q8d/optgEIGMZOAAvoHn4GJUiGXIl/1Dz2XJ2z0MRBLzSLTUOBxtCq5IyCboQeN8vJmOjtntdiqsVgBgaGhRYIvYzOfeZJY/IHEWh9UXS7nDvmJAe18RawtM2mVev/kT28M3PMEZRhcQVhS/V0V+1xl0YoRNOM+LIhlN8Qi2FcS5L5FkTsagNqb8he6KI41i2h/FiZ/i/DSKlKjEkcqZM71zv21Sp00FUOL0MPNswuaCjyqHsNVRVcuxfa3JmIRl19SibkAEt9+do4bJ8cUe8HaAUCXrbYIyCs7kbv1lHh7KnepYRs38w0TufrgDinRb6XKDuUYWAhxEvaV9pSPnaEh2zlq/L9L+gZASSK6a/8ca7xFcUB8="
