script: bash ./deploy.sh
language: node_js
node_js:
- "4.0"
env:
  global:
  - GH_REF: github.com/rikukissa/rikurouvila.fi.git
  - secure: "VPk979xHr32BgFx3TplcD/J11DEHTy9E0LmZmimNWVUl1SvQO+0MexCnbmiJYy7Im27acKsduuKkd9iIt3wxsOYOGOl5WkRQSuaLa6kUidmjKr/1lpWJcro6lhYEVREw7QtBJ+iPKYIHatxFQsrh0Bx47/xXY95IQ7Yw98XvMo8Jf3HJjY88QLOlsdhP0/YNZ/cOZALdtXX1gBu3yRsjGqQDcKF9c0A+R3t93JNzJNe/ao6UyuyFg6zqFwY4VHCyluZuGDiyDe2utQLZ8nJo3Bui/zW/L3gT5hqvPBtc7//vsdnIlmYEQcC6Z284DPZ55C+LrPIf8UL8LvEFJTV1K16wPqHS3mowdNT/8DaKsoTKhvX4E5yz8ZuC2Mm2dygGXlX8MS1+7p+0oXvB/niUpadcGBHMaQyckA58Of5nJftzD/YKNL/1SiS039WZlatnCj4itVJZpSNp1khhs26Ziwgek7XlAQA6X3II4vlnHs7KKULdJty9a2vgpOHpIgUyi+8FxykE/AxoCEgx7JuupUNIb23DPLfDu7/z3f8iDmHEr7T3I7aluzfQUT221vNpmFOPGuBCJYYonFVW+iTCXli1xnHyuO8bFIBhzYwp1mo/0RkG344pLieOWOvc9VguuLkum0XRT2hdI0fBXOkJaTdr7XOpm6g6qu8zVZA62Uk="
